const tableColumns = {
  //slice 3->35
  name: "String",
  //select from array index: 0-100
  price: "Number",
  //slice 3->70
  bulletOne: "String",
  //slice 3->70
  bulletTwo: "String",
  //slice 3->70
  bulletThree: "String",
  //slice 3->35
  sellerName: "String",
  //slice 3->255
  description: "String",
  productID: "Number"
};

const nameString =
  "dnqjdwligqiwbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce";
const arrayString1 = [
  "nrgwierngcworjwnocw",
  "uwnvzoehrg",
  "siygdwiwehbfweifybwliyefbwehirufnw",
  "fjflwbeliwdheliwhdniluhwflycgilw",
  "hfw7lieuhrgiuhvr8g",
  "j",
  "weh",
  "fbwehir",
  "hdniluhwflycgilwhncliwehf",
  "wirncerwhncilhr93hcwiunf",
  "rj",
  "hbfweifybwliyefbwehirufnwkwflej",
  "vr8gouwnvzoehrg",
  "gdwiwehbfwe",
  "7",
  "nf",
  "flicbhrfh",
  "v",
  "ehfcim",
  "flycgilwhncliwehfci",
  "gqiwbdhbqlsiygd",
  "nfjflwbeliwdheliwhdniluhwflycg",
  "eliwdheliwh",
  "uwnvzoehrgilncnrgwi",
  "gcworjwnocwlihewirncerwhn",
  "dwligqiwbdhbqls",
  "nfjflwbeliwdheliwhdniluh",
  "cwiunflicbhrfhcnphxefiuwhxwno",
  "rgwierngcworjwnocwl",
  "gc",
  "iwehbfweifybwliyefbwehirufnwkwflejf",
  "lhfw7lieuhrgiuhvr",
  "rgilncnrgwierngcworjwnoc",
  "bwliyefbwehirufnwkwflejf",
  "ngcworjwn",
  "siygdwi",
  "licbhrf",
  "wflycgilwhncliwehfcim",
  "iwbdhbqlsiygdwiwehbfweifybwliyef",
  "ehrgil",
  "vzoehrgilncnrgwi",
  "beliwdheliwhdniluhw",
  "ilwhncliwehfcimlhfw",
  "ieuhrgiuhvr8gouwnvzoehrgilncnr",
  "jflwb",
  "whncliwehfcimlhf",
  "qjdwligqiwbdhbqlsiygdwiweh",
  "uhwflycgilwhncliwehfcimlh",
  "hr93hcwiunflicbhrfhcnphxef",
  "ybwliyefbwehirufnwkwfl",
  "bwe",
  "erngcworjwnoc",
  "licbh",
  "whdniluhwflycgilwhnc",
  "wehirufnwkwflejfnfjflwbeliwdhe",
  "uhvr8gouwn",
  "cnrgwierngcworjwnocwlihewi",
  "lncnrgwierngc",
  "siygdwiw",
  "hr93hcwiunflicbhrfhcnphxefiuwh",
  "erngcworjwnocwlih",
  "whncliwehfcimlhfw7lieuhrgiuhvr8gouw",
  "gwierngcworjwnocwlihew",
  "wehfcimlhfw7lieuhrgiuhvr8gouwnvzoeh",
  "l",
  "lihewirncerwhncilhr93hcwiun",
  "rgwierngcworjwnocwlihewirn",
  "",
  "yefbwehirufnwkwflejfnfjflwbeliwdhe",
  "eliwhdniluhwflycgilwhncliweh",
  "hcwiunflicbhrfhcnphxefiuwh",
  "eliwdheliwhdniluh",
  "f",
  "erwhncilhr93hcwiunflicbhrfh",
  "luhwflycgilwh",
  "ejfnfjflwbeliw",
  "ngcworj",
  "",
  "worjwnocwlihewirncerw",
  "liwehfcimlhfw7l",
  "zoehrgilncnrgwierngcworjwn",
  "fcimlhfw7lieuhrgiuhvr8gouwnvzoehr",
  "uhvr8gouwnvzoehrgilncnrgwie",
  "beli",
  "jfnfjflwbeliwdheli",
  "lsiygdwiwehbfweifybwliyefbwehirufnw",
  "nqjdwligqiwbdhbqlsiygdwiwehb",
  "bqlsiygdwi",
  "wi",
  "wliyefbwehirufnwkwflejfnf",
  "nfjfl",
  "rncerwhncil",
  "ehbfweifybwliyefbwehirufnwkwfle",
  "flycgilwhncliwehfcimlhfw7lieuhrg",
  "hr93hcwiunflicbhrfhcnphxefi",
  "liwehfcimlhfw7lieuhrgiuhvr8gou",
  "liwehfcimlhfw7lieuhrgiuhvr8",
  "wiunflicbhrfhcnphxefiuwhx",
  "ocwlihewirnce",
  "ejfnfjflwbel"
];
const arrayString2 = [
  "fweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgil",
  "uhwflycgilwhncliwehfcimlhfw7lieuhrgiuh",
  "wkwflejfnfjflwbel",
  "cgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouw",
  "iwdheliwhdniluhwflyc",
  "igqiwbd",
  "hn",
  "cwlihewirncerwhncilhr93h",
  "fbwehirufnwkwflejfnf",
  "bfweifybwliyefbwehiru",
  "93hcwiunflicbhrfhcnphxefiuwhxwnotwhei",
  "hbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluh",
  "dhbqlsiygdwiwehbfweifybwliyefbwehirufn",
  "dhbqlsiygdwiwehbfweifybwliyefbw",
  "hfw7",
  "lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncer",
  "r93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgh",
  "heliwhdniluhwflycgilwhncliw",
  "ligqiwbdhbqlsiygdwiwehbfweifybwliyefbwehiruf",
  "hwflycgilwhncliwe",
  "whncliwehfcimlhfw7lie",
  "hncliwehfcimlhfw7lieuhrgiuhvr8gouwnvz",
  "wehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7li",
  "iwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgil",
  "lejfnfjflw",
  "w7lieuhrgiuhvr8gouwnvzoehrgilncnrgwie",
  "liwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrg",
  "iwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilw",
  "ncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufc",
  "qlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbe",
  "ifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdnil",
  "ocwlihewir",
  "bqlsiygdwiwehbfweifybwliyefbwehiru",
  "hncilhr93hcwiunflicbhrf",
  "ieuhrgiuhvr",
  "wkwflejfnfjflwbeliwdheliwhdniluhwflycgilw",
  "iwhdniluhwflycgil",
  "dwligqiwbdhbqlsiygdwiwehbf",
  "dwligqiwbdhbqlsi",
  "hirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lie",
  "eliwdheliwhdniluhwflycgilwhncliwehf",
  "",
  "ilncnrgwierngc",
  "irufnwkwflejfnfjflwbeliwdheliwhdni",
  "nflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileur",
  "bqlsiygdwiwehbfwe",
  "igqiwbdhbqlsiy",
  "ufnwkwflejfnfjflwbel",
  "hwflycgilwhncliwehfcimlhfw7lieuhrgi",
  "rufnwkwfl",
  "rgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhc",
  "vr8",
  "wbeliwdheliwhdniluhwf",
  "worjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnp",
  "bwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwh",
  "7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerw",
  "ehrgilncnrgwierngcworjwnocwlihewirncerwhncil",
  "hwflycgilwhncliwehfcimlhfw7",
  "fbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycg",
  "qiwbd",
  "j",
  "r8gouwnvzoehrg",
  "j",
  "dwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbe",
  "fbwehirufnwkwflejfnfjflwbeliwdhe",
  "ncliw",
  "flwbeli",
  "wbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflw",
  "gi",
  "ybwliyefbwehir",
  "gouwnvzoehrgilncnrgwierngcworjwnocwli",
  "wliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilw",
  "erwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwe",
  "uwnvzoehrgilncnrgwiern",
  "r8gouwnvzoehrgilncnrgwierngcworjwnocwli",
  "fjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuh",
  "jfnfjflwbeliwdhe",
  "eliwdheliwhdn",
  "hrgilncnrgwierngcworjwnocwlihewirncerwh",
  "whncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierng",
  "giuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihe",
  "qlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbe",
  "lwbeliwdheliwhdniluhwflycgilwhncliw",
  "uhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnoc",
  "ngcworjwnocwlih",
  "hncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufch",
  "lwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrg",
  "dwiwehbfweifybwli",
  "ncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwier",
  "wirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiuf",
  "gqiwbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwfle",
  "flejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhf",
  "lhfw7lieuhrgiuhvr",
  "giuhvr8gouwnvzoehrgilncnrgwierngcwor",
  "nwkwflejfnfjflwbeliwdheliwhdniluhwflycgi",
  "whdniluhwf",
  "hcwiunflicbhrfhcnphxefiuwhxwnotw",
  "rgwierngcworjwn",
  "w7lieuhrgiuhvr8gouwnvzoehrgilncnrgwie",
  "siygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluh"
];

const arrayString3 = [
  "fweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhnc",
  "uhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufch",
  "wkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnph",
  "cgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "iwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgil",
  "igqiwbdhbqlsiygdwiwehbfweifybwliyefbwehirufnw",
  "hncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "cwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "fbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "bfweifybwliyefbwehirufnwkwflejfnfjfl",
  "93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrc",
  "hbqlsiygd",
  "dhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncli",
  "dhbqls",
  "hfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrc",
  "lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "r93hcwiunflic",
  "heliwhdniluhwflycgi",
  "ligqiwbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuh",
  "hwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcct",
  "whncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlih",
  "hncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncn",
  "wehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhx",
  "iwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnp",
  "lejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgher",
  "w7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcw",
  "liwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "iwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyj",
  "ncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "qlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwiern",
  "ifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrg",
  "ocwlihewirncerwhncilhr93hcwiunflicbh",
  "bqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecghe",
  "hncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "ieuhrgiuhvr8gouwnvzoehrgilncnrgwier",
  "wkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "iwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgiln",
  "dwligqiwbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrg",
  "dwligqiwbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncl",
  "hirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhn",
  "eliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwh",
  "ycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuh",
  "ilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwn",
  "irufnwkwflejfnfjflwbeliwdhe",
  "nflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "",
  "igqiwbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnr",
  "ufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhnc",
  "hwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwhe",
  "rufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "rgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "vr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "wbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwhe",
  "worjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnx",
  "bwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgiln",
  "7lieuh",
  "ehrgilncnrgwierngcworjwnocwlihew",
  "hwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "fbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwie",
  "qiwbdhbqlsiyg",
  "jfnfj",
  "r8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "jflwbeliwdheliwhd",
  "dwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxn",
  "fbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwn",
  "ncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "flwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "wbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwhei",
  "gilwhncliwehfci",
  "ybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "wliyefbwehirufnwkwflejfnfjfl",
  "erwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "uwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "r8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxil",
  "fjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhnc",
  "jfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehff",
  "eliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihew",
  "hrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunfli",
  "whncliwehfcimlhfw7lie",
  "giuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "qlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngc",
  "lwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxn",
  "uhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileur",
  "ngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "hncilhr93hcwiunflicbhrfhcnphxefiuwh",
  "lwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8",
  "dwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdn",
  "ncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileur",
  "wirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuh",
  "gqiwbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflej",
  "flejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfih",
  "lhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnr",
  "giuhvr8gouwnvzoehrgilncnrgwierng",
  "nwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwhe",
  "whdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "rgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "w7lieuhrgiuhvr8gouwnvzoehrgilncnrgwierngcworjwnocwlihewirncerwhncilhr93hcwiunflicbhrfhcnphxefiuwhxwnotwheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce",
  "siygdwiwehb"
];
const priceNumber = [
  "$1.00",
  "$1.01",
  "$1.02",
  "$1.03",
  "$1.04",
  "$1.05",
  "$1.06",
  "$1.07",
  "$1.08",
  "$1.09",
  "$1.10",
  "$1.11",
  "$1.12",
  "$1.13",
  "$1.14",
  "$1.15",
  "$1.16",
  "$1.17",
  "$1.18",
  "$1.19",
  "$1.20",
  "$1.21",
  "$1.22",
  "$1.23",
  "$1.24",
  "$1.25",
  "$1.26",
  "$1.27",
  "$1.28",
  "$1.29",
  "$1.30",
  "$1.31",
  "$1.32",
  "$1.33",
  "$1.34",
  "$1.35",
  "$1.36",
  "$1.37",
  "$1.38",
  "$1.39",
  "$1.40",
  "$1.41",
  "$1.42",
  "$1.43",
  "$1.44",
  "$1.45",
  "$1.46",
  "$1.47",
  "$1.48",
  "$1.49",
  "$1.50",
  "$1.51",
  "$1.52",
  "$1.53",
  "$1.54",
  "$1.55",
  "$1.56",
  "$1.57",
  "$1.58",
  "$1.59",
  "$1.60",
  "$1.61",
  "$1.62",
  "$1.63",
  "$1.64",
  "$1.65",
  "$1.66",
  "$1.67",
  "$1.68",
  "$1.69",
  "$1.70",
  "$1.71",
  "$1.72",
  "$1.73",
  "$1.74",
  "$1.75",
  "$1.76",
  "$1.77",
  "$1.78",
  "$1.79",
  "$1.80",
  "$1.81",
  "$1.82",
  "$1.83",
  "$1.84",
  "$1.85",
  "$1.86",
  "$1.87",
  "$1.88",
  "$1.89",
  "$1.90",
  "$1.91",
  "$1.92",
  "$1.93",
  "$1.94",
  "$1.95",
  "$1.96",
  "$1.97",
  "$1.98",
  "$1.99"
];

const dummyData = [
  {
    name: "name1a",
    price: "$9.99",
    bulletOne: "string1a",
    bulletTwo: "string2a",
    bulletThree: "string3a",
    sellerName: "string4a",
    description: "string5a"
  },
  {
    name: "bname1",
    price: "$9.99",
    bulletOne: "bstring1",
    bulletTwo: "bstring2",
    bulletThree: "bstring3",
    sellerName: "bstring4",
    description: "bstring5"
  },
  {
    name: "n1",
    price: "$9.99",
    bulletOne: "s1",
    bulletTwo: "s2",
    bulletThree: "s3",
    sellerName: "s4",
    description: "s5"
  },
  {
    name: "1n1",
    price: "$9.99",
    bulletOne: "1s1",
    bulletTwo: "2s2",
    bulletThree: "3s3",
    sellerName: "4s4",
    description: "5s5"
  }
];

// const nameString = "dnqjdwligqiwbdhbqlsiygdwiwehbfweifybwliyefbwehirufnwkwflejfnfjflwbeliwdheliwhdniluhwflycgilwhncliwehfcimlhfw7lieuhrgiuhvr8gouwnvtoehrgilncnrgwierngcworj;nocwlihewirncerwhncilhr93hcwiunflicbhrfhcn;hxefiuwhx;no;wheiufchhnxfuhnxfihuwecgherinxileurhgxnreuhilehffjtycycyjcctrce";
array1 = [];
array2 = [];
array3 = [];
let randomStartIndex1 = 0;
let randomStartIndex2 = 0;
let randomStartIndex3 = 0;
for (let i = 0; i < 100; i++) {
  randomStartIndex1 = Math.floor(Math.random(0) * 186);
  randomStartIndex2 = Math.floor(Math.random(0) * 186);
  randomStartIndex3 = Math.floor(Math.random(0) * 253);
  array1.push(
    nameString.slice(
      randomStartIndex1,
      randomStartIndex1 + Math.floor(Math.random(3) * 36)
    )
  );
  array2.push(
    nameString.slice(
      randomStartIndex2,
      randomStartIndex2 + Math.floor(Math.random(3) * 71)
    )
  );
  array3.push(
    nameString.slice(
      randomStartIndex2,
      randomStartIndex2 + Math.floor(Math.random(3) * 255)
    )
  );
}
console.log(array1);
console.log(array2);
console.log(array3);
